name: example
description: Minimal host app for store_screenshots_generator.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.10.7

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  intl: any
  flutter_localizations:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  store_screenshots_generator:
    path: ../
  flutter_lints: ^6.0.0

flutter:
  generate: true
  uses-material-design: true
