import 'dart:io';

import 'package:yaml/yaml.dart';

import '../composition/composition_dart_emitter.dart';
import '../composition/studio_project_factory.dart';
import '../config/config_loader.dart';
import '../config/models/screenshot_config.dart';

/// Scaffolds a host Flutter app for store screenshots (init / auto-ensure).
class ProjectScaffold {
  static const initHeader =
      '// GENERATED BY store_screenshots_generator:init — re-run init --force to replace.';

  /// Creates missing scaffold files under [hostRoot]. Returns paths written.
  static List<String> ensure({
    required String hostRoot,
    bool force = false,
  }) {
    final root = Directory(hostRoot).absolute.path;
    final pubspecFile = File('$root${Platform.pathSeparator}pubspec.yaml');
    if (!pubspecFile.existsSync()) {
      throw StateError('pubspec.yaml not found in $root');
    }

    final packageName = _readPackageName(pubspecFile);
    final manifest = _readManifestOrDefault(root);
    final emitter = CompositionDartEmitter();
    final emptyProject = StudioProjectFactory.fromManifest(
      manifest: manifest,
      name: packageName,
    );

    final written = <String>[];

    void writeIfMissing(String relativePath, String content) {
      final file = File('$root${Platform.pathSeparator}$relativePath');
      if (!force && file.existsSync()) return;
      file.parent.createSync(recursive: true);
      file.writeAsStringSync(content);
      written.add(relativePath);
    }

    writeIfMissing(
      'screenshots.yaml',
      _screenshotsYamlTemplate(),
    );
    writeIfMissing(
      'lib${Platform.pathSeparator}store_screenshots${Platform.pathSeparator}layout_registry.dart',
      emitter.emitRegistry(),
    );
    writeIfMissing(
      'lib${Platform.pathSeparator}store_screenshots${Platform.pathSeparator}generated${Platform.pathSeparator}project.dart',
      emitter.emitProject(emptyProject),
    );
    writeIfMissing(
      'lib${Platform.pathSeparator}store_screenshots${Platform.pathSeparator}generated${Platform.pathSeparator}compositions.dart',
      emitter.emitCompositions(const {}),
    );
    writeIfMissing(
      'test${Platform.pathSeparator}store_screenshots_test.dart',
      _storeExportTestTemplate(packageName),
    );
    writeIfMissing(
      'test${Platform.pathSeparator}raw_screenshots_test.dart',
      _rawCaptureTestTemplate(packageName),
    );

    return written;
  }

  static bool needsScaffold(String hostRoot) {
    final root = Directory(hostRoot).absolute.path;
    final required = [
      'screenshots.yaml',
      'test${Platform.pathSeparator}store_screenshots_test.dart',
      'lib${Platform.pathSeparator}store_screenshots${Platform.pathSeparator}generated${Platform.pathSeparator}project.dart',
    ];
    return required.any((path) => !File('$root${Platform.pathSeparator}$path').existsSync());
  }

  static String _readPackageName(File pubspecFile) {
    final doc = loadYaml(pubspecFile.readAsStringSync());
    if (doc is! YamlMap) {
      throw FormatException('Invalid pubspec.yaml at ${pubspecFile.path}');
    }
    final name = doc['name']?.toString();
    if (name == null || name.isEmpty) {
      throw FormatException('pubspec.yaml is missing "name"');
    }
    return name;
  }

  static ProjectConfig _readManifestOrDefault(String hostRoot) {
    final configFile = File(
      '$hostRoot${Platform.pathSeparator}screenshots.yaml',
    );
    if (configFile.existsSync()) {
      return loadProjectConfigFromYaml(configFile.readAsStringSync());
    }
    return const ProjectConfig(
      devices: ['iphone_15_pro', 'pixel_8'],
      locales: ['en-US'],
      rawScreenshotsPath: 'raw_screenshots',
      statusBar: 'dark',
    );
  }

  static String _screenshotsYamlTemplate() => '''
# Technical scope for capture tests and export loops (no store slots here).
rawScreenshotsPath: raw_screenshots
statusBar: dark

devices:
  - iphone_15_pro
  - pixel_8

locales:
  - en-US
''';

  static String _storeExportTestTemplate(String packageName) => '''
$initHeader

import 'package:$packageName/store_screenshots/layout_registry.dart';
import 'package:store_screenshots_generator/store_screenshots_generator.dart';

void main() {
  runStoreScreenshotExportTests(
    loadProject: loadGeneratedStudioProject,
  );
}
''';

  static String _rawCaptureTestTemplate(String packageName) => '''
$initHeader
// ignore_for_file: avoid_print

import 'dart:io';

import 'package:$packageName/main.dart';
import 'package:flutter/material.dart';
import 'package:flutter/services.dart';
import 'package:flutter_test/flutter_test.dart';
import 'package:store_screenshots_generator/store_screenshots_generator.dart';

/// Captures raw PNGs for the Layout Studio raw pool.
///
/// Edit the [captures] list with your app routes and capture ids.
void main() {
  setUpAll(() async {
    debugDisableShadows = false;
    await loadScreenshotTestFonts();

    final materialIconPath =
        '\${Platform.environment['FLUTTER_ROOT'] ?? ''}'
        '/bin/cache/artifacts/material_fonts/MaterialIcons-Regular.otf';
    if (File(materialIconPath).existsSync()) {
      final iconData = File(materialIconPath).readAsBytesSync();
      final loader = FontLoader('MaterialIcons');
      loader.addFont(Future.value(iconData.buffer.asByteData()));
      await loader.load();
    }
  });

  testWidgets('Capture raw screenshots', (WidgetTester tester) async {
    addTearDown(() => debugDisableShadows = true);

    const deviceId = String.fromEnvironment(
      'DEVICE',
      defaultValue: 'iphone_15_pro',
    );
    const locale = String.fromEnvironment('LOCALE', defaultValue: 'en-US');

    final device = DeviceRegistry.getById(deviceId);
    final resolution = device.resolution;
    final pixelRatio = device.pixelRatio;

    final logicalSize = Size(
      resolution.width / pixelRatio,
      resolution.height / pixelRatio,
    );

    await tester.binding.setSurfaceSize(logicalSize);
    tester.view.physicalSize = resolution;
    tester.view.devicePixelRatio = pixelRatio;

    final rootKey = GlobalKey();
    await tester.pumpWidget(
      ScreenshotScaffold(
        boundaryKey: rootKey,
        device: device,
        child: MyApp(locale: locale),
      ),
    );
    await tester.pumpAndSettle();

    final context = tester.element(find.byType(Navigator));

    const captures = <({String id, String route})>[
      (id: 'home', route: '/'),
    ];

    for (final capture in captures) {
      print('Capturing \${capture.id} (\$deviceId, \$locale)...');
      Navigator.pushReplacementNamed(context, capture.route);
      await tester.pumpAndSettle();

      await captureRawScreenshot(
        tester,
        screenshotId: capture.id,
        locale: locale,
        deviceId: deviceId,
        boundaryKey: rootKey,
      );
    }

    await tester.binding.setSurfaceSize(null);
    tester.view.resetPhysicalSize();
    tester.view.resetDevicePixelRatio();
    debugDisableShadows = true;
  });
}
''';
}
