// GENERATED BY store_screenshots_generator:init — re-run init --force to replace.

import 'package:example/store_screenshots/layout_registry.dart';
import 'package:store_screenshots_generator/store_screenshots_generator.dart';

void main() {
  runStoreScreenshotExportTests(
    loadProject: loadGeneratedStudioProject,
  );
}
