import 'models/composition.dart';
import 'models/scene_element.dart';
import 'models/store_slot.dart';
import 'models/studio_project.dart';

/// Emits generated Dart for [StudioProject] compositions.
class CompositionDartEmitter {
  static const header = '// GENERATED BY Layout Studio — do not edit.';

  String emitProject(StudioProject project) {
    final buffer = StringBuffer()
      ..writeln(header)
      ..writeln()
      ..writeln(
        "import 'package:store_screenshots_generator/store_screenshots_generator.dart';",
      )
      ..writeln()
      ..writeln("import 'compositions.dart';")
      ..writeln()
      ..writeln('/// Generated studio project metadata.')
      ..writeln('StudioProject loadGeneratedStudioProject() {')
      ..writeln('  return StudioProject(')
      ..writeln("    name: '${_escape(project.name)}',")
      ..writeln('    deviceIds: ${_stringList(project.deviceIds)},')
      ..writeln('    locales: ${_stringList(project.locales)},')
      ..writeln('    slots: ${_slotsList(project.slots)},')
      ..writeln(
        "    rawScreenshotsPath: '${_escape(project.rawScreenshotsPath)}',",
      )
      ..writeln('    compositions: kGeneratedCompositions,')
      ..writeln('  );')
      ..writeln('}')
      ..writeln();

    return buffer.toString();
  }

  String emitCompositions(Map<String, Composition> compositions) {
    final buffer = StringBuffer()
      ..writeln(header)
      ..writeln()
      ..writeln(
        "import 'package:store_screenshots_generator/store_screenshots_generator.dart';",
      )
      ..writeln()
      ..writeln('const Map<String, Composition> kGeneratedCompositions = {');

    for (final entry in compositions.entries) {
      buffer.writeln(
        "  '${_escape(entry.key)}': ${_compositionLiteral(entry.value)},",
      );
    }

    buffer
      ..writeln('};')
      ..writeln();

    return buffer.toString();
  }

  String emitRegistry() {
    return '''
$header

export 'generated/compositions.dart';
export 'generated/project.dart';
''';
  }

  String _compositionLiteral(Composition composition) {
    final elements =
        composition.elements.map(_elementLiteral).join(',\n      ');
    return '''Composition(
    elements: [
      $elements,
    ],
  )''';
  }

  String _elementLiteral(SceneElement element) {
    final props = _propertiesLiteral(element.properties);
    return '''SceneElement(
      id: '${_escape(element.id)}',
      type: ElementType.${element.type.name},
      frame: ElementFrame(
        x: ${element.frame.x},
        y: ${element.frame.y},
        width: ${element.frame.width},
        height: ${element.frame.height},
        rotation: ${element.frame.rotation},
      ),
      properties: $props,
    )''';
  }

  String _propertiesLiteral(Map<String, dynamic> properties) {
    if (properties.isEmpty) return 'const {}';
    final entries = properties.entries.map((e) {
      return "'${_escape(e.key)}': ${_valueLiteral(e.value)}";
    });
    return '{${entries.join(', ')}}';
  }

  String _valueLiteral(dynamic value) {
    if (value is bool) return value ? 'true' : 'false';
    if (value is int) return '$value';
    if (value is double) return value.toString();
    if (value is String) return "'${_escape(value)}'";
    if (value is Map) {
      final entries = value.entries.map(
        (e) =>
            "'${_escape(e.key.toString())}': '${_escape(e.value.toString())}'",
      );
      return '{${entries.join(', ')}}';
    }
    if (value is List) {
      final items = value.map(_valueLiteral);
      return '[${items.join(', ')}]';
    }
    return "'${_escape(value.toString())}'";
  }

  String _slotsList(List<StoreSlot> slots) {
    final items = slots.map((s) {
      final presetPart = s.presetId == null
          ? ''
          : ", presetId: '${_escape(s.presetId!)}'";
      final rawPart = s.rawCaptureId == null
          ? ''
          : ", rawCaptureId: '${_escape(s.rawCaptureId!)}'";
      return "StoreSlot(id: '${_escape(s.id)}', name: '${_escape(s.name)}'$presetPart$rawPart)";
    });
    return '[${items.join(', ')}]';
  }

  String _stringsList(List<String> values) {
    return '[${values.map((v) => "'${_escape(v)}'").join(', ')}]';
  }

  String _stringList(List<String> values) => _stringsList(values);

  String _escape(String value) => value.replaceAll("'", r"\'");
}
